apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: morning-hero-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-key-vault
    kind: ClusterSecretStore
  target:
    name: morning-hero-secrets
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: morning-hero-prod-database-url
    - secretKey: SESSION_SECRET
      remoteRef:
        key: morning-hero-session-secret
    - secretKey: ADMIN_PIN
      remoteRef:
        key: morning-hero-admin-pin
